### ISSUE TITLE
Commits pushed to 8.x-2.x branch do not get replicated to drupal.org

### ISSUE THREAD

**Issue by mondrake** [drupal-media/image_effects#1]
When pushing commits to the 8.x-1.x branch, the webhook replicates them to the corresponding branch on d.o.

However, no replication occurs for commits pushed to the 8.x-2.x branch, so they need to be pushed manually to d.o. too. Also, tags pushed to either 1.x or 2.x do not get replicated, so when making releases on d.o. we need to push them manually.

Maybe @slashrsm can you check this?

**Comment by slashrsm** [comment]
Every branch needs a separate job in Jenkins. Created one for 8.x-2.x: https://ci.drupalmedia.org/job/image_effects%208.x-2.x/

Should work now.

**Comment by mondrake** [comment]
Thanks @slashrsm!

I have no commits to push now :) but will check at the soonest occasion.

**Comment by slashrsm** [comment]
Cool. I'll close for now. If you experience any problems feel free to re-open.
